Models/CarService.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace GarageProject.Models
{
    public class CarService
    {
        public int Id { get; set; }

        [Required]
        [RegularExpression(@"^(?:(?:\+|0{0,2})91(\s*[\ -]\s*)?|[0]?)?[789]\d{9}|(\d[ -]?){10}\d$", ErrorMessage = "Miles Cannot Contain Alphabetic Character")]
        public int Miles { get; set; }

        [Required]
        [RegularExpression(@"^(?:(?:\+|0{0,2})91(\s*[\ -]\s*)?|[0]?)?[789]\d{9}|(\d[ -]?){10}\d$", ErrorMessage = "Price Cannot Contain Alphabetic Character")]
        public double Price { get; set; }

        [Required]
        public string Details { get; set; }

        [Required]
        public string ServiceType { get; set; }

        public int CarId { get; set; }

        [ForeignKey("CarId")]
        public Car Car { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}")]
        public DateTime DateAdded { get; set; }


        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}")]
        public DateTime Requested { get; set; }
    }
}

Controllers/CarServicesController.cs
using GarageProject.Models;
using GarageProject.ViewModel;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Formatting;
using System.Web;
using System.Web.Mvc;

namespace GarageProject.Controllers
{
    [Authorize]
    public class CarServicesController : Controller
    {
        ApplicationDbContext db;

        public CarServicesController()
        {
            db = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
        }

    
        public ActionResult Create(Car car)
        {
            var viewModel = new CarAndServiceViewModel()
                {
                    CarServicesDbs=db.CarServicesDbs.ToList(),
                    Cars=car                    
                };

                return View(viewModel);           
           
        }



        [HttpPost]
        public ActionResult Create(CarAndServiceViewModel viewModel)
        {
            //viewModel.ServiceCar.CarId = viewModel.Cars.Id;
            //viewModel.ServiceCar.DateAdded = DateTime.Today;

            var vM = new ServiceRequest()
            {
               CarId=viewModel.Cars.Id,
               DateRequested=DateTime.Today,
               Details=viewModel.ServiceCar.Details,
               Miles=viewModel.ServiceCar.Miles,
               Price=viewModel.ServiceCar.Price,
               ServiceType=viewModel.ServiceCar.ServiceType,
               UserId=User.Identity.GetUserId()
            };

            db.ServiceRequests.Add(vM);
            db.SaveChanges();


            
            return RedirectToAction("Index","User");
        }
        
        public ActionResult Approve()
        {
            IEnumerable<ServiceRequest> requests = db.ServiceRequests.ToList();

            var vModel = new UserCarServiceReqViewModel()
            {
                Requests=requests,
                Cars=db.Cars.ToList(),
                Users=db.Users.ToList()
            };

            return View(vModel);
        }


        
        public ActionResult Approved(int ? id)
        {
            var sReq = db.ServiceRequests.Find(id);
            CarService cSer = new CarService()
            {
                //Car=db.Cars.Find(sReq.CarId),
                CarId=sReq.CarId,
                Requested=sReq.DateRequested,
                DateAdded=DateTime.Today,
                Details=sReq.Details,
                Miles=sReq.Miles,
                Price=sReq.Price,
                ServiceType=sReq.ServiceType               
            };

            string uri = "https://localhost:44346/api/service";
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(uri);
                JsonMediaTypeFormatter formatter = new JsonMediaTypeFormatter();
                //HTTP POST
                var postTask = client.PostAsync<CarService>("service", cSer, formatter);       //PutAsJsonAsync<Customer>("customers", customer);
                postTask.Wait();

                var result = postTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var remSerReq = db.ServiceRequests.Find(id);
                    db.ServiceRequests.Remove(remSerReq);
                    db.SaveChanges();
                    return RedirectToAction("Approve");
                }
            }

            return View();
        }

       
        public ActionResult Decline(int ? id)
        {
            var ser=db.ServiceRequests.Find(id);
            db.ServiceRequests.Remove(ser);
            db.SaveChanges();
            return RedirectToAction("Approve");
        }




            // GET: CarServices
            public ActionResult ViewServices(Car car)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://localhost:44346/api/");
                var responsetask = client.GetAsync("service?id="+car.Id);
                responsetask.Wait();

                var result = responsetask.Result;
                JsonMediaTypeFormatter formatter = new JsonMediaTypeFormatter();
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<IEnumerable<CarService>>();
                    readTask.Wait();

                    var viewModel = new CarAndServiceViewModel()
                    {
                        CarServices=readTask.Result,
                        Cars=car,
                        PendingRequests=db.ServiceRequests.ToList()
                    };
                    return View(viewModel);
                }
            }
            return View();
        }


        public ActionResult Requests(ApplicationUser user)
        {
            return View();
        }
    }
}

Views/CarServices/Approve.cshtml
@model GarageProject.ViewModel.UserCarServiceReqViewModel
@{
    ViewBag.Title = "Approve";
}

<h2 style="text-align:center;">Service Requests</h2>
@if (ViewContext.HttpContext.User.IsInRole("admin"))
{
    using (Html.BeginForm("Approved", "CarServices"))
    {
        <div>

            @if (Model.Requests.Any())
            {
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>User</th>
                            <th>Email</th>
                            <th>Car VIN</th>
                            <th>Car Model</th>
                            <th>Car Style</th>
                            <th>Miles</th>
                            <th>Details</th>
                            <th>Service Type</th>
                            <th>Price</th>
                            <th>Date Requested</th>
                            <th></th>
                            <th></th>
                        </tr>
                    </thead>
                    @foreach (var req in Model.Requests)
                    {

                        <tbody>
                            <tr>
                                <td>@Model.Users.Where(c => c.Id.Equals(req.UserId)).SingleOrDefault().FirstName</td>
                                <td>@Model.Users.Where(c => c.Id.Equals(req.UserId)).SingleOrDefault().UserName</td>
                                <td>@Model.Cars.Where(c => c.Id == req.CarId).SingleOrDefault().VIN</td>
                                <td>@Model.Cars.Where(c => c.Id == req.CarId).SingleOrDefault().Model</td>
                                <td>@Model.Cars.Where(c => c.Id == req.CarId).SingleOrDefault().Style</td>
                                <td>@req.Miles</td>
                                <td>@req.Details</td>
                                <td>@req.ServiceType</td>
                                <td>@req.Price</td>
                                <td>@req.DateRequested</td>
                                @*@{
                                        req.Price = Convert.ToInt32(ViewData["PriceVal"]);
                                    }*@
                                <td>@Html.ActionLink("Approve", "Approved", "CarServices", new { req.Id }, new { @class = "btn btn-success" })</td>
                                @*<td><button type="submit" class="btn btn-success">Approve</button></td>*@
                                <td>@Html.ActionLink("Decline", "Decline", "CarServices", new { req.Id }, new { @class = "btn btn-warning" })</td>


                            </tr>
                        </tbody>
                    }
                    @Html.HiddenFor(c => c.Requests)
                </table>

            }

            else
            {
                <h3 style="text-align:center">No Pending Requests</h3>
            }



        </div>
    }
}

Views/CarServices/Create.cshtml
@model GarageProject.ViewModel.CarAndServiceViewModel
@{
    ViewBag.Title = "Create";
}

<h1 style="text-align:center;">Add Service</h1>

<div class="jumbotron  field-validation-error">
    @using (Html.BeginForm())
    {
        <table class="table form-group field-validation-valid field-validation-error">
            <tr>
                <td class="form-group" style="color:chocolate;">
                    @Html.LabelFor(m => m.ServiceCar.Miles)
                </td>
                <td class="form-group" style="color:chocolate;">
                    @Html.TextBoxFor(m => m.ServiceCar.Miles, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.ServiceCar.Miles)
                </td>
                <td class="form-group" style="color:chocolate;">
                    @Html.LabelFor(m => m.ServiceCar.Details)
                </td>
                <td class="form-group" style="color:chocolate;">
                    @Html.TextBoxFor(m => m.ServiceCar.Details, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.ServiceCar.Details)

                </td>

            </tr>
            <tr>
                <td class="form-group" style="color:chocolate;">
                    @Html.Label(" Bearable Cost")
                </td>
                <td class="form-group" style="color:chocolate;">
                    @Html.TextBoxFor(m => m.ServiceCar.Price, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.ServiceCar.Price)

                </td>
                <td class="form-group" style="color:chocolate;">
                    @Html.LabelFor(m => m.ServiceCar.ServiceType)
                </td>
                <td class="form-group" style="color:chocolate;">
                    @Html.DropDownListFor(m => m.ServiceCar.ServiceType, new SelectList(Model.CarServicesDbs, "CarServicesData", "CarServicesData"), "Select Service type", new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.ServiceCar.ServiceType)

                </td>
            </tr>

        </table>
        @Html.HiddenFor(m => m.Cars.Id)
        @*<button class="btn btn-primary" type="submit" onclick="Update()">Submit Service Request</button>*@
        <button class="btn btn-primary" type="submit" onclick="Update()">Submit Service Request</button>

        <div class="alert alert-danger" id="passwordsNoMatchRegister" style="display:none;">
            <strong>Error!</strong> Looks like the passwords you entered don't match!
        </div>
    }
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
@Scripts.Render("~/bundles/toastr")
<script type="text/javascript">
    function Update() {
        setTimeout(function () {
            sub
        }, 100000);
        toastr.success('Submitted Succesfully', 'Submit', { timeOut: 0 });
    }
//var funcBtns = {
//    Update:function(){
//        toastr.success('Request Submitted Succesfully', 'Submission', { timeOut: 1000 }, {extentedTimeOut:0 });
//    }
//};
</script>
}

Views/CarServices/ViewServices.cshtml
@model GarageProject.ViewModel.CarAndServiceViewModel
@{
    ViewBag.Title = "ViewServices";
}

<br />
<br />
@section css{
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.css" />

}
@{
    var carSer = Model.Cars;
    carSer.Model = Model.Cars.Model;
    carSer.Style = Model.Cars.Style;
    carSer.Color = Model.Cars.Color;
    carSer.VIN = Model.Cars.VIN;
    carSer.ApplicationUserId = Model.Cars.ApplicationUserId;
}
<div>
    <table class="table table-hover table-bordered results" style="background-color:gray;">
        <thead>
            <tr style="text-align:center;font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif; color:white;font-size:15px;">
                <th class="col-md-2 col-xs-2" style="text-align:center;"> Brand </th>
                <th class="col-md-2 col-xs-2" style="text-align:center;"> Style </th>
                <th class="col-md-2 col-xs-2" style="text-align:center;"> Model </th>
                <th class="col-md-2 col-xs-2" style="text-align:center;"> Color</th>
            </tr>
        </thead>
        <tbody>
            <tr style="text-align:center;font-family:'Berlin Sans FB';">
                <td>@Model.Cars.Brand</td>
                <td>@Model.Cars.Style</td>
                <td>@Model.Cars.Model</td>
                <td>@Model.Cars.Color</td>
            </tr>
        </tbody>
    </table>

</div>

@if (Model.CarServices.Any())
{

    <div>
        <h2 style="text-align:center;">Service Details</h2>
        <table id="service" class="table table-hover table-bordered results" style="background-color:gray;">
            <thead>
                <tr style="text-align:center;font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif; color:white;font-size:15px;">
                    <th class="col-md-2 col-xs-2" style="text-align:center;"> Miles </th>
                    <th class="col-md-2 col-xs-2" style="text-align:center;"> Price </th>
                    <th class="col-md-2 col-xs-2" style="text-align:center;"> Details</th>
                    <th class="col-md-2 col-xs-2" style="text-align:center;"> Service Type</th>
                    <th class="col-md-2 col-xs-2" style="text-align:center;"> Date Requested</th>
                    <th class="col-md-2 col-xs-2" style="text-align:center;"> Date Added</th>
                    @if (ViewContext.HttpContext.User.IsInRole("admin"))
                    {
                        <th class="col-md-1 col-xs-1" style="text-align:center;"></th>
                    }
                </tr>
            </thead>
            <tbody>
                @foreach (var ser in Model.CarServices)
                {
                    if (ser.CarId == Model.Cars.Id)
                    {
                        <tr style="text-align:center;font-family:'Berlin Sans FB';">
                            <td>@ser.Miles</td>
                            <td>@ser.Price</td>
                            <td>@ser.Details</td>
                            <td>@ser.ServiceType</td>
                            <td>@ser.Requested.ToLongDateString()</td>
                            <td>@ser.DateAdded.ToLongDateString()</td>
                            @if (ViewContext.HttpContext.User.IsInRole("admin"))
                            {
                                <td><button class="btn btn-danger fa fa-trash fa-1x jq-delete " data-customer="@ser.Id" type="button"> </button></td>
                            }
                        </tr>
                    }
                }

            </tbody>
        </table>

    </div>
}
else
{
    <p> No Service Yet</p>
}
@{
    if (!ViewContext.HttpContext.User.IsInRole("admin"))
    {
        @Html.ActionLink(" Request Service", "Create", "CarServices", carSer, new { @class = "btn btn-warning" })

    }
    @*else
        {
            <button class="btn akkBtn-dark fa  fa-user-plus">@Html.ActionLink("Request Service", "Create", "CarServices", Model.Cars, new { })</button>

        }*@
}
<hr />

@if (Model.PendingRequests.Any())
{

    <div>
        <h2 style="text-align:center;">Pending Service Requests</h2>
        <table id="service" class="table table-hover table-bordered results" style="background-color:gray;">
            <thead>
                <tr style="text-align:center;font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif; color:white;font-size:15px;">
                    <th class="col-md-2 col-xs-2" style="text-align:center;"> Miles </th>
                    <th class="col-md-2 col-xs-2" style="text-align:center;"> Price </th>
                    <th class="col-md-2 col-xs-2" style="text-align:center;"> Details</th>
                    <th class="col-md-2 col-xs-2" style="text-align:center;"> Service Type</th>
                    <th class="col-md-2 col-xs-2" style="text-align:center;"> Date Requested</th>
                    @if (ViewContext.HttpContext.User.IsInRole("admin"))
                    {
                        <th class="col-md-1 col-xs-1" style="text-align:center;"></th>
                    }
                </tr>
            </thead>
            <tbody>
                @foreach (var ser in Model.PendingRequests)
                {
                    if (ser.UserId == Model.Cars.ApplicationUserId)
                    {
                        <tr style="text-align:center;font-family:'Berlin Sans FB';">
                            <td>@ser.Miles</td>
                            <td>@ser.Price</td>
                            <td>@ser.Details</td>
                            <td>@ser.ServiceType</td>
                            <td>@ser.DateRequested.ToLongDateString()</td>
                            @if (ViewContext.HttpContext.User.IsInRole("admin"))
                            {
                                <td><button class="btn btn-danger fa fa-trash fa-1x jq-delete " data-customer="@ser.Id" type="button"> </button></td>
                            }
                        </tr>
                    }
                }

            </tbody>
        </table>

    </div>
}
else
{
    <h3 style="text-align:center"> No Pending Request</h3>
}
@section scripts{
    <script>
        $(document).ready(function () {
            $('#service .jq-delete').on('click', function () {
                var button = $(this)
                if (confirm('Confirm Delete ?')) {
                    $.ajax({
                        url: '/api/service/' + $(this).attr('data-customer'),
                        method: 'DELETE',
                        success: function () {
                            button.parents('tr').remove()
                        }
                    })
                }
            })
        })
    </script>
}

